"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from corsheaders.defaults import default_headers as cors_default_headers
from dotenv import load_dotenv

# from user.models.users import CustomUser

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Must run before anything below calls os.getenv, or that setting silently falls
# back to its default: load_dotenv() does not retroactively fix a value already
# read. (runserver used to mask this -- its reloader re-imports settings in a
# child process that inherits the environment the first pass had populated.)
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Development escape hatch. With DEV_OPEN_NETWORK=True the API accepts any Host
# header and any CORS origin, so an ngrok tunnel, a phone on the LAN, or a
# teammate's machine can reach it without adding each new URL to a list.
# It is deliberately ANDed with DEBUG: if DEBUG is off the flag does nothing,
# so switching a deployment to production closes this even if the variable is
# left set in the environment. Never enable it on a public deployment.
DEV_OPEN_NETWORK = DEBUG and os.getenv('DEV_OPEN_NETWORK', 'False').lower() in ('true', '1', 'yes')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'rest_framework',
    'corsheaders',
    'user'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'user.middleware.AutoLogoutMiddleware' # Custom middleware to logout user after 30 minutes of inactivity
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use DATABASE_URL (e.g. a local Postgres) if set, otherwise fall back to Supabase.
db_url = os.getenv('DATABASE_URL') or os.getenv('SUPABASE_DB_URL')

DATABASES = {
    'default': dj_database_url.parse(
        db_url,
        conn_max_age=0,  # Don't persist connections with pooler
        conn_health_checks=True,  # Check connection health before using
        ssl_require=os.getenv('DB_SSL_REQUIRE', 'True').lower() in ('true', '1', 'yes')
    )
}

# Enable connection health checks
CONN_HEALTH_CHECKS = True

SUPABASE_DB_URL = os.environ.get("SUPABASE_DB_URL")

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# The business runs on Manila time. Left at UTC, every localtime() call and
# every date bucket flipped its day at 08:00 Manila -- mid-morning. Stored
# timestamps are unaffected (USE_TZ keeps them UTC); only interpretation.
TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/api/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOW_CREDENTIALS = True
#CORS settings to allow request 
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://10.0.2.2",
    "https://biolock.astrosail.site",
    "http://biolock.astrosail.site",
    "http://localhost",
    "http://127.0.0.1",
    "http://10.0.2.2:8000",
]

CSRF_TRUSTED_ORIGINS = [
    "https://biolock.astrosail.site",
    "http://biolock.astrosail.site",
    # ngrok tunnels used for on-device testing
    "https://*.ngrok-free.app",
    "https://*.ngrok-free.dev",
    "https://*.ngrok.app",
    "https://*.ngrok.io",
]

# django-cors-headers' defaults (accept, authorization, content-type, user-agent,
# x-csrftoken, x-requested-with) plus anything extra we need. Never use ['*'] here:
# CORS_ALLOW_CREDENTIALS is on, and for credentialed requests the browser matches
# Access-Control-Allow-Headers literally, so a wildcard blocks every real header.
CORS_ALLOW_HEADERS = list(cors_default_headers) + [
    'ngrok-skip-browser-warning',
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'OPTIONS',
    'PATCH',
]

if DEV_OPEN_NETWORK:
    # Accept every host and echo back whichever origin asks. CORS_ALLOW_CREDENTIALS
    # stays on, and django-cors-headers echoes the request origin rather than "*"
    # in that case, so cookies and auth headers keep working through a tunnel.
    ALLOWED_HOSTS = ['*']
    CORS_ALLOW_ALL_ORIGINS = True
    import sys as _sys
    print(
        "\n  WARNING: DEV_OPEN_NETWORK is on -- every host and origin is accepted.\n"
        "  This is for local testing only. Turn it off in .env before deploying.\n",
        file=_sys.stderr,
    )

#Custom User Model
AUTH_USER_MODEL = 'user.CustomUser'


REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        # 'rest_framework.throttling.AnonRateThrottle',  # Limits anonymous users
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'user.authentication.CookieTokenAuthentication',  # Use your actual path
        # Other authentication classes if needed
    ],
    'DEFAULT_THROTTLE_RATES': {
    #     'anon': '100/hour',  # Set rate for anonymous users
    #     'user': '1000/day',  # Set rate for authenticated users
    #     'login': '5/min'  # Limit 5 login attempts per minute
    },
    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
    ],
    
    
}

# Session expires after 30 minutes of inactivity
SESSION_COOKIE_AGE = 1800  # 1800 seconds = 30 minutes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Logs out user when they close the browser
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on each request

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

GOOGLE_CALENDAR_CREDENTIALS_JSON_PATH = os.path.join(BASE_DIR, 'google_credentials', 'credentials.json')
PHILIPPINE_HOLIDAY_CALENDAR_ID = 'en.philippines#holiday@group.v.calendar.google.com'

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

BASE_DIR_FIREBASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'user', 'biolock.json')