# Generated by Django 5.1.5 on 2025-01-25 10:02

from django.db import migrations, models

def create_default_roles(apps, schema_editor):
    Role = apps.get_model('user', 'Role')
    Role.objects.get_or_create(role_name='admin')
    Role.objects.get_or_create(role_name='user')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
